name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    defaults:
      run:
        working-directory: frogger

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get elvis
      uses: actions/checkout@v2
      with:
        repository: inaka/elvis
        path: elvis
    - name: Build elvis
      run: cd elvis && rebar3 escriptize
    - name: Run elvis
      run: |
        elvis/_build/default/bin/elvis rock
    - name: Dialyzer
      run: cd elvis && rebar3 dialyzer
    # - name: Compile
    #   run: rebar3 compile
    # - name: Run tests
    #   run: rebar3 do eunit, ct
